### ISSUE TITLE
Adding more content control on Article/Text area

### ISSUE THREAD

**Issue by justiny** [kamilczujowski/least.js-2#7]
Hey,

First, thanks for the cool script.  I'm enjoying it!

I wanted to ask about adding some areas to the article text area, which is the .least-preview class that is appended?  I'm wondering if instead of adding content via data-caption, I could allow to add more content in the html rather than the script?  

Thanks again!

**Comment by kamilczujowski** [comment]
Hey!

This is a great point! I'm working currently on this task! :)
