### ISSUE TITLE
'scrollToGallery': false breaks plugin

### ISSUE THREAD

**Issue by pieter-biesemans** [kamilczujowski/least.js-2#9]
Since you only call preventdefault in the scrollToGallery function, the preview will only work when scrollToGallery is enabled.

When set to false, the browser will just open the link.

SOLUTION: always call preventdefault on the link

**Comment by mware** [comment]
Pieter, could you give an example of how to fix this? Thx.

**Comment by pieter-biesemans** [comment]
So this is your code. It only works when scrollToGallery is set to true. When set to false, the preventDefault is never called, so the link keeps working as a link:
```javascript
            /* Scroll to Top */
            if(settings.scrollToGallery) {
                $(this).find('li a').click(
                    function(e) {
                        e.preventDefault();
                    }
                );
            }
```

The easiest fix for this is just to call preventDefault on all links in the least gallery. I just did this at the bottom of my page, but it can be easily incorporated in the least.js file.
```javascript
$('.least-gallery li a').click(function(){
    e.preventDefault();
})
```

**Comment by kamilczujowski** [comment]
Hey Guys,

sorry for the late answer and thank's for your' fix.
It's coming with the next version (2.3) very soon!

**Comment by pieter-biesemans** [comment]
no problem, you're welcome!
